// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLatk14AUOhIL7lDAPaW_nO_lHKXB06M',
    appId: '1:748195029433:web:4aaf34562b504823e49668',
    messagingSenderId: '748195029433',
    projectId: 'monprojet-4b04c',
    authDomain: 'monprojet-4b04c.firebaseapp.com',
    storageBucket: 'monprojet-4b04c.appspot.com',
    measurementId: 'G-ZVL9JCRYGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqI1nMmh1sG3YLR5XUUYiEsqPB9hFveLk',
    appId: '1:748195029433:android:4c168907bf6ccf33e49668',
    messagingSenderId: '748195029433',
    projectId: 'monprojet-4b04c',
    storageBucket: 'monprojet-4b04c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0GbfO0fnGgetj-7XvG1Z9fPz759lKdIk',
    appId: '1:748195029433:ios:42ccbb752837d727e49668',
    messagingSenderId: '748195029433',
    projectId: 'monprojet-4b04c',
    storageBucket: 'monprojet-4b04c.appspot.com',
    iosClientId:
        '748195029433-9roo2bi1omvdslvp938km4969v93bvhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0GbfO0fnGgetj-7XvG1Z9fPz759lKdIk',
    appId: '1:748195029433:ios:caab1d251885af67e49668',
    messagingSenderId: '748195029433',
    projectId: 'monprojet-4b04c',
    storageBucket: 'monprojet-4b04c.appspot.com',
    iosClientId:
        '748195029433-t3ak1gkt8loq8k9323tormq06cg2k0ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication7.RunnerTests',
  );
}
